services:
     - type: web
       name: bookstore-api
       env: java
       region: singapore # Closest to your location (Sri Lanka); alternatives: oregon, ohio, frankfurt
       plan: free
       branch: main
       repo: https://github.com/Jehanfernando02/BookstoreAPI # Replace with your repo URL
       buildCommand: mvn clean package
       startCommand: java -jar target/bookstore-1.0.jar
       healthCheckPath: /api/health # Optional: Add a health check endpoint
       envVars:
         - key: JAVA_OPTS
           value: -Xms512m -Xmx512m # Limit memory for free tier