services:
  - type: web
    name: bookstore-api
    env: docker
    region: singapore
    plan: free
    branch: main
    repo: https://github.com/Jehanfernando02/BookstoreAPI
    healthCheckPath: /api/health
    envVars:
      - key: JAVA_OPTS
        value: -Xms512m -Xmx512m
      - key: PORT
        value: 8080